server:
  port: 8000

spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]': ## aplica a todas las rutas
                allowed-origin-patterns: "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTION # React
                  - PATCH
                allowed-headers: "*"
                allow-credentials: true

          routes:
            - id: usuario-service
              uri: lb://usuario-service # lb buscara el servicio en eureka si esta disponible
              predicates:
                - Path=/api/usuarios/**, /api/auth/**

            - id: post-service
              uri: lb://post-service
              predicates:
                - Path=/api/posts/**

            - id: media-service
              uri: lb://media-service
              predicates:
                - Path=/api/media/**

            - id: interaccion_service
              uri: lb://interaccion-service
              predicates:
                - Path=/api/interacciones/**

            - id: chat-service
              uri: lb://chat-service
              predicates:
                - Path=/api/chat/**, /ws-chat/**

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}