spring:
  application:
    name: media-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    # Limite de archivo (fotos)
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


server:
  port: 9093

media:
  storage:
    location: {MEDIA_STORAGE_LOCATION:./uploads}


eureka:
  client:
    service-url:
      ## si el servicio esta en este mismo pc usar localhost
      ## si eureka server esta en otro pc entonces la ip de ese pc junto a :8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    #envia la ip real del microservicio a eureka en lugar del nombre
    # de su computador
    prefer-ip-address: true
